### ISSUE TITLE
cant install pip dependencies thus not working!!

### ISSUE THREAD

**Issue by mahmed0715** [feross/Instant.fm#253]
Hi,
When i try to install pip dependencies there are lots of errors,
Tried using pillow, but not solved,
Can you please check!
Thanks in advance

**Comment by mahmed0715** [comment]
Cant get it working ..
lots if issues with dependencies and rendering !!
can you please check!!
thanks in advance..

**Comment by feross** [comment]
Sorry, this is not supported anymore. You'll have to figure it out for yourself.
